accessWidener v2 named
accessible field net/minecraft/src/NBTTagList tagList Ljava/util/List;
accessible field net/minecraft/src/NBTTagCompound tagMap Ljava/util/Map;
extendable method net/minecraft/src/Item getIconIndex (Lnet/minecraft/src/ItemStack;)Lnet/minecraft/src/Icon;
accessible field net/minecraft/src/Entity entityUniqueID Ljava/util/UUID;
accessible field net/minecraft/src/RenderManager entityRenderMap Ljava/util/Map;
accessible field net/minecraft/src/GuiChat field_73905_m Z
accessible field net/minecraft/src/GuiChat inputField Lnet/minecraft/src/GuiTextField;
accessible field net/minecraft/src/GuiScreen mc Lnet/minecraft/src/Minecraft;
accessible field net/minecraft/src/GuiIngame remainingHighlightTicks I
accessible class net/minecraft/src/EntityAITaskEntry
accessible field net/minecraft/src/EntityAIAvoidEntity targetEntityClass Ljava/lang/Class;
accessible field net/minecraft/src/EntityAINearestAttackableTarget targetClass Ljava/lang/Class;
mutable field net/minecraft/src/EntityAINearestAttackableTarget targetClass Ljava/lang/Class;
accessible field net/minecraft/src/EntityLiving targetTasks Lnet/minecraft/src/EntityAITasks;
accessible field net/minecraft/src/WeightedRandomChestContent theItemId Lnet/minecraft/src/ItemStack;
accessible field net/minecraft/src/WeightedRandomChestContent theMinimumChanceToGenerateItem I
accessible field net/minecraft/src/WeightedRandomChestContent theMaximumChanceToGenerateItem I
accessible field net/minecraft/src/WeightedRandomItem itemWeight I
accessible field net/minecraft/src/WorldGenDungeons field_111189_a [Lnet/minecraft/src/WeightedRandomChestContent;
accessible field net/minecraft/src/EntityAITasks taskEntries Ljava/util/List;
accessible field net/minecraft/src/EntityLiving tasks Lnet/minecraft/src/EntityAITasks;
accessible field net/minecraft/src/EntityAINearestAttackableTarget targetEntity Lnet/minecraft/src/EntityLivingBase;
accessible field net/minecraft/src/EntityHorse horseChest Lnet/minecraft/src/AnimalChest;
accessible field net/minecraft/src/EntityList classToStringMapping Ljava/util/Map;
accessible method net/minecraft/src/WorldType <init> (ILjava/lang/String;)V
accessible field net/minecraft/src/TextureAtlasSprite animationMetadata Lnet/minecraft/src/AnimationMetadataSection;
accessible field net/minecraft/src/PlayerControllerMP currentGameType Lnet/minecraft/src/EnumGameType;
accessible field net/minecraft/src/MobSpawnerBaseLogic spawnCount I
accessible field net/minecraft/src/MobSpawnerBaseLogic spawnRange I
accessible field net/minecraft/src/MobSpawnerBaseLogic maxNearbyEntities I
accessible field net/minecraft/src/MobSpawnerBaseLogic maxSpawnDelay I
accessible field net/minecraft/src/MobSpawnerBaseLogic minSpawnDelay I
accessible field net/minecraft/src/MobSpawnerBaseLogic minecartToSpawn Ljava/util/List;
extendable method net/minecraft/src/BlockPane canThisPaneConnectToThisBlockID (I)Z
accessible field net/minecraft/src/Entity isImmuneToFire Z
accessible method net/minecraft/src/EntityLiving getLivingSound ()Ljava/lang/String;
accessible method net/minecraft/src/ItemDye applyBoneMeal (Lnet/minecraft/src/World;III)Z
accessible method net/minecraft/src/DamageSource <init> (Ljava/lang/String;)V
accessible field net/minecraft/src/EffectRenderer particleTextures Lnet/minecraft/src/ResourceLocation;
accessible field net/minecraft/src/EntityList stringToClassMapping Ljava/util/Map;
accessible field net/minecraft/src/EntityHorse horseJumpStrength Lnet/minecraft/src/Attribute;
accessible field net/minecraft/src/RenderBiped field_110859_k Ljava/util/Map;
accessible field net/minecraft/src/SaveHandler playersDirectory Ljava/io/File;
